### PR TITLE
Update

### PR DESCRIPTION
**Pull request by mokhtarabadi**

### CODE REVIEW

**Comment by conectapb** [comment]
Nobody knows how to fix this error?
00qgi

**Comment by tjhorner** [comment]
It's not an error. You need to plug it into your computer and open a debugger such as Android Studio

**Comment by conectapb** [comment]
@tjhorner  Ja fiz isso amigo, ja ativei no celular, troquei de celular tudo ja tentei

**Comment by tjhorner** [comment]
That's the Telegram Beta application, are you sure you want that?

**Comment by conectapb** [comment]
@tjhorner  This friend'm testing with the beta, I tried with the other version is also more the sam

**Comment by ShalbafZadeh** [comment]
@mokhtarabadi i dont think this amount of changes would be acceptable with a single commit
and you've changed fundamentals of Telegram Android app

**Comment by ziahot935** [comment]
Add me

**Comment by conectapb** [comment]
What is your email? @ziahot935  portalgazetadaparaiba@bol.com.br

**Pull request closed without merging**
