### PR TITLE
How to change the theme colors telegram

### PR DESCRIPTION
**Pull request by conectapb**
@DrKLO @Bubu @zhukov @slp @yorlov 
friends you know how to change the theme colors? I've tried here and I find the right option ... Hugs

### CODE REVIEW

**Comment by EhsaanF** [comment]
Pull request isn't a place to ask a question/feature. Also "Issues" are out, so looks like they don't want feature ask from their users.

**Comment by meysamkp** [comment]
Hi dear DrKLO,

The last few days I've been trying to call you for a good cooperation, but unfortunately you were not responsive in telegram, whether it is possible to start a dialogue within the telegram to send me a message.
My phone number: +989390783729
Email: meysamkp@yahoo.com

Thanks,
Meysam.

**Comment by ADTC** [comment]
I knew this would happen if the issue page is closed for business.

**Comment by g1hostsilvestre** [comment]
Generate the .apk on Android Studio when I install the phone the following error message "Sorry! Unfortunately, the App stopped. "

Gero o Apk no Android Studio quando instalo no celular a seguinte mensagem de erro “ Desculpe! Infelizmente, o App parou.”

**Comment by ajju4455** [comment]
@g1hostsilvestre You need to post your logcat with Error Log. there must be some Exception.

**Pull request closed without merging**
