### PR TITLE
Add Simplified Chinese support.

### PR DESCRIPTION
**Pull request by pexcn**
Language sheets from: https://t.me/zh_CN channel.

### CODE REVIEW

**Comment by tonghuix** [comment]
Please merge it!

**Comment by wfjsw** [comment]
No they won't give comments on this
https://core.telegram.org/tsi/bios#7-new-language-requests

**Comment by bzzbzz7** [comment]
gratefull

**Comment by pexcn** [comment]
@DrKLO Can you merge it?

**Comment by wfjsw** [comment]
https://t.me/zh_CN won't ever exist if they merge

**Comment by wfjsw** [comment]
Forget it. It is a duplicate of #96, #360, #954, #957, #965, #1284 and various of (hidden) issues.

**Comment by barreeeiroo** [comment]
I'm not sure if @DrKLO will merge...
Translations are done in Transifex and then added to the project before release
So, if you would like to add a new language maybe you need to request in the Transifex project

**Comment by wfjsw** [comment]
@barreeeiroo Actually Transifex Project has that language and it is fully translated already.
Don't know why they don't accept new members

**Comment by pexcn** [comment]
Closed due to inactivity.

**Pull request closed without merging**
