### PR TITLE
Fix incompatibility with Gradle plugin on Windows.

### PR DESCRIPTION
**Pull request by DanAlbert**
When run on Windows, the shell does not handle the argument quoting
and this is seen by gradle as `'-DVERSION="1.3.1"'` rather than as
`-DVERSION="1.3.1"`, which gradle wrongly interprets as a source file.

### CODE REVIEW

**Comment by Aokromes** [comment]
this is telegram android, are you sure you are targeting the correct repo?

**Comment by Amirhf1** [comment]
Please give one correct instruction to run the source

**Comment by DanAlbert** [comment]
Open it in Android Studio and build it.

**Comment by team0NE** [comment]
In new 5.2.0 version got the same problem. Solution is similar -> TProj/jni/Android.mk line number 545
LOCAL_CFLAGS += '-DVERSION="1.3.1"' -DFLAC__NO_MD5 -DFLAC__INTEGER_ONLY_LIBRARY -DFLAC__NO_ASM 
change to:
LOCAL_CFLAGS += -DVERSION="1.3.1" -DFLAC__NO_MD5 -DFLAC__INTEGER_ONLY_LIBRARY -DFLAC__NO_ASM 
Hope this will help

**Comment by Rave-Tian** [comment]
> In new 5.2.0 version got the same problem. Solution is similar -> TProj/jni/Android.mk line number 545
> `LOCAL_CFLAGS += '-DVERSION="1.3.1"' -DFLAC__NO_MD5 -DFLAC__INTEGER_ONLY_LIBRARY -DFLAC__NO_ASM `
> change to:
> `LOCAL_CFLAGS += -DVERSION="1.3.1" -DFLAC__NO_MD5 -DFLAC__INTEGER_ONLY_LIBRARY -DFLAC__NO_ASM `
> Hope this will help

it works! thanks dude, this help me a lot.

**Comment by aabolfazl** [comment]
i have this problem but icant fix it with 
LOCAL_CFLAGS += -DVERSION="1.3.1" -DFLAC__NO_MD5 -DFLAC__INTEGER_ONLY_LIBRARY -DFLAC__NO_ASM

**Comment by aabolfazl** [comment]
> In new 5.2.0 version got the same problem. Solution is similar -> TProj/jni/Android.mk line number 545
> `LOCAL_CFLAGS += '-DVERSION="1.3.1"' -DFLAC__NO_MD5 -DFLAC__INTEGER_ONLY_LIBRARY -DFLAC__NO_ASM `
> change to:
> `LOCAL_CFLAGS += -DVERSION="1.3.1" -DFLAC__NO_MD5 -DFLAC__INTEGER_ONLY_LIBRARY -DFLAC__NO_ASM `
> Hope this will help

i have this problem but icant fix it with
LOCAL_CFLAGS += -DVERSION="1.3.1" -DFLAC__NO_MD5 -DFLAC__INTEGER_ONLY_LIBRARY -DFLAC__NO_ASM

**Pull request closed without merging**
