### PR TITLE
Add "Themed Icon for Android 13 and higher"

### PR DESCRIPTION
**Pull request by Attorelle**
Since @the-dise has been promising a vector icon for some time, but has been modifying social media apps all along, I decided to do it for him.

:shrug:

### CODE REVIEW

**Review by clownless — APPROVED** [review]

**Review by whyredow — APPROVED** [review]
nice

**Review by Sominemo — APPROVED** [review]

**Comment by the-dise** [comment]
photo_2022-05-03_12-30-55
Wrong size vector icon.

**Review by the-dise — CHANGES_REQUESTED** [review]
Icon has wrong size. Need to make it smaller.

**Comment by Attorelle** [comment]
> Icon has wrong size.

Um.. thanks, I got fixed this :thinking:
Blind editing ruins everything

**Comment by the-dise** [comment]
> > Icon has wrong size.
> 
> Um.. thanks, I got fixed this 🤔 Blind editing ruins everything

I've already added an icon in my pull and remake it.

**Review by itsreallyv1eds — APPROVED** [review]

**Comment by marcselman** [comment]
Will this be merged anytime soon?

**Review by Qwessd1 — APPROVED** [review]

**Comment by marcselman** [comment]
This feature is already live in the current version from the store.

**Review by Qwessd1 — APPROVED** [review]

**Pull request closed without merging**
