### PR TITLE
Create help

### PR DESCRIPTION
**Pull request by sannikov**
Please, give it to Pavel Durov. Governments. Physics. I'm waiting for communication.

### CODE REVIEW

**Comment by SmartManoj** [comment]
> Please, give it to Pavel Durov. Governments. Physics. I'm waiting for communication.

Spam?

**Review by Fran19979 — COMMENTED** [review]
- .

**Comment by SmartManoj** [comment]
> * .

?

**Comment by peach-lasagna** [comment]
изображение

**Comment by yatkau** [comment]
Что это? Похоже на шизофазию.

**Comment by sannikov** [comment]
Please add a comment to delete this pull request.

**Comment by peach-lasagna** [comment]
> 
> 
> Please add a comment to delete this pull request.

изображение

**Pull request closed without merging**
