### PR TITLE
Stop using Trackers (This app is not private)

### PR DESCRIPTION
**Pull request by shalaga44**
This app is tracking us using :

# Google Firebase Analytics 

# Microsoft Appcenter Analytics

# Microsoft Appcenter Crashes

Competed using [Exodus Privacy Analytics](https://exodus-privacy.eu.org)
The Official App doesn't use any kind of tracking systems

# If you care about your privacy don't use this App

### CODE REVIEW

**Comment by alissonlauffer** [comment]
You can try Telegram FOSS if you care about these trackers.

**Comment by shalaga44** [comment]
@alissonlauffer I'm already using it 👾

**Comment by skiezest** [comment]
FYI, Telegram X has no trackers

**Comment by Mushebeq** [comment]
Degenerate pull

**Pull request closed without merging**
