### PR TITLE
Themed Icon for Android 13

### PR DESCRIPTION
**Pull request by the-dise**
Please add support for themed icon for Android 13
Screenshot_20220429-134907

### CODE REVIEW

**Comment by IvanMihienko** [comment]
And monet themes, it will be a good 😊

**Comment by IvanMihienko** [comment]
And monet themes, it will be a good 😊

**Review by storm2513 — APPROVED** [review]

**Comment by Attorelle** [comment]
But.. this is a **png**... For monochrome icons it's better to use **svg**.

**Comment by the-dise** [comment]
No problem, I can offer a pull tomorrow with a vector icon

**Review by iTaysonLab — APPROVED** [review]

**Review by Sominemo — APPROVED** [review]

**Review by Attorelle — APPROVED** [review]

**Review by itsreallyv1eds — APPROVED** [review]

**Review by KOT4N — APPROVED** [review]

**Review by fuccsoc — APPROVED** [review]

**Review by s0ftik3 — APPROVED** [review]

**Review by clownless — APPROVED** [review]

**Comment by Attorelle** [comment]
> No problem, I can offer a pull tomorrow with a vector icon

I did this instead of u lol
https://github.com/DrKLO/Telegram/pull/1702

**Review by Sominemo — APPROVED** [review]

**Review by s0ftik3 — APPROVED** [review]

**Review by Playez — APPROVED** [review]

**Review by clownless — APPROVED** [review]

**Review by Sominemo — APPROVED** [review]

**Review by Fustie — APPROVED** [review]

**Review by PerchunPak — APPROVED** [review]

**Comment by ArchGryphon9362** [comment]
Guys, awakening this thread because I'm pretty sure it's now allowed! Yes please and thank yous :)

**Review by mashirozx — APPROVED** [review]

**Review by sunny7498 — APPROVED** [review]

**Pull request closed without merging**
