### PR TITLE
Added Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by Z-Shang**
Translated by micweiyi and I.

### CODE REVIEW

**Comment by Z-Shang** [comment]
This is the first draft, we are going to review it within a week

**Comment by rubenlagus** [comment]
@Z-Shang  Translation were moved to  https://www.transifex.com/projects/p/telegram, better have a look at https://core.telegram.org/translating_telegram too.

**Comment by Z-Shang** [comment]
KK, thanks for that

**Comment by dkaraush** [comment]
Translations are now available at https://translations.telegram.org/, feel free to contribute there

**Pull request closed without merging**
