### PR TITLE
Updates in Readme.md Line 39

### PR DESCRIPTION
**Pull request by VarunPathak17**

### CODE REVIEW

**Comment by avarayr** [comment]
This is spam.

**Comment by andresribeiro** [comment]
This Pull Request is not necessary. You should close it 

@DrKLO

**Comment by huezo** [comment]
@DrKLO Please update Telegram in Huawei AppGallery.

Screenshot_20210204_120402_com huawei appmarket

**Comment by EMAMIANK455** [comment]
A۹

در تاریخ پنجشنبه ۴ فوریهٔ ۲۰۲۱،‏ ۲۱:۳۹ HUEZO <notifications@github.com>
نوشت:

**Comment by EMAMIANK455** [comment]
A۹

**Comment by huezo** [comment]
Please update the Telegram version of Huawei Appgalery!!

[appgallery Telegram](https://appgallery.huawei.com/#/app/C101184875)




https://appgallery.huawei.com/#/app/C101184875

**Comment by dkaraush** [comment]
Oh

**Pull request closed without merging**
