### PR TITLE
Added catalan language

### PR DESCRIPTION
**Pull request by efcacar**
File with catalan translations.

### CODE REVIEW

**Comment by carstenhag** [comment]
Perhaps relevant: https://github.com/DrKLO/Telegram#localization

**Comment by efcacar** [comment]
In these website catalan language is not available. For that reason I've translated the application with Android Studio and I pushed the xml file.

**Comment by ftyers** [comment]
@carstenhag not all languages are available on the Telegram site. Aside from Catalan, Chuvash is also not available.

captura de 2018-02-14 16-51-54

Is the right thing to do submit pull requests as @efcacar has done, or is there somewhere that issues can be filed for languages missing in the list ?

**Comment by Ecron** [comment]
@omkarnathsingh @efcacar there’s already a Catalan project, which has been developed by [Softcatalà](https://github.com/softcatala) with the translations done properly, and supported by the Catalan community.

The link to the translation project in Transifex is https://www.transifex.com/telegram-unofficial-translations/public/

The Catalan language packs that you can find in the bot named Langbot (t.me/langbot) are fetched from that project.

If you are going to add Catalan language to the Android app, please add the file from that Transifex project, for it’s been developed by an experienced team through many years of work.

**Comment by omkarnathsingh** [comment]
I appreciate that unofficial project, but its always better to have these small things officially, as it will allow users to have latest features in app.

**Comment by Ecron** [comment]
So what do you mean, @omkarnathsingh? You approved the changes in this PR. Does it mean that the Catalan translation provided by @efcacar will be added officially to the Android app? Because it's full of errors and it doesn't follow the Softcatalà's [Style Guide](https://www.softcatala.org/guia-estil-de-softcatala/) (standard nowadays for app translations into Catalan) (No ofenses, @efcacar, I know you did a hard work :+1: ).

**Comment by efcacar** [comment]
I am not offended @Ecron, I am not a proffesional translator, don't worry. Why Softcatalà pull the project and translate it officially? It is not difficult. Or I can take the translations from Transifex and push to this project. But I think that Sofcatlà does the translations officially is the best way.

**Comment by Ecron** [comment]
@efcacar Softcatalà do the translations "officially", in the meaning that they officially translate Telegram apps into Catalan. But Telegram LLC won't accept Softcatalà's translations by the moment as an "official language supported by Telegram". That's why Softcatalà's translations are by the moment "unofficial", and you can find them both in [@langbot](https://t.me/langbot) and [@SoftcatalaBot](https://t.me/softcatalabot).

The moment Telegram LLC accepts Softcatalà's translations, they will become "officially official".

**Comment by 123georgesteve** [comment]
I do apologize for the inconvenience this may cause I have stepped away
from everything.  My wife totaled the car , now in the hospital, I am mom
and dad .

**Comment by dkaraush** [comment]
As I see, Catalan is now available at https://translations.telegram.org/, so I am gonna close the PR.
I see 900 strings there untranslated, so that can be the reason why it is not available in the language list right now. Feel free to use langpacks.

**Pull request closed without merging**
