### PR TITLE
increase MAX_ACCOUNT_COUNT

### PR DESCRIPTION
**Pull request by wrwrabbit**
increase MAX_ACCOUNT_COUNT = 5

### CODE REVIEW

**Comment by wrwrabbit** [comment]
Related issue https://github.com/DrKLO/Telegram/pull/1575

**Comment by ctwoon** [comment]
it won't work like this

**Comment by wrwrabbit** [comment]
> it won't work like this

@ctwoon wouldn't it work like mentioned in https://github.com/DrKLO/Telegram/pull/1575#issuecomment-683489255 ?

**Comment by ctwoon** [comment]
@wrwrabbit sure, I've done it like this in my fork.

**Comment by wrwrabbit** [comment]
> @wrwrabbit sure, I've done it like this in my fork.

Thanks. Yes, works well

**Comment by dkaraush** [comment]
Increased! As a premium feature though 🕺

**Pull request closed without merging**
