### PR TITLE
Change Search rule

### PR DESCRIPTION
**Pull request by ikicha**
past : startwith
now : contains

### CODE REVIEW

**Comment by JunnanZ** [comment]
I think it's related to this issue about searching in Asian languages https://github.com/telegramdesktop/tdesktop/issues/564. 

@DrKLO Could you think of a way to reconcile that?

**Comment by mrr010** [comment]
> It's wrong, people never search in name "Nickolai" substring "kol", they always search name from start.

Chinese language user always/only search like that because every Chinese character is a word by itself without spaces seperated. The current search functions is useless for us.

**Comment by kmvan** [comment]
Need this feature.

**Comment by spphinslove** [comment]
> 
> 
> It's wrong, people never search in name "Nickolai" substring "kol", they always search name from start.

Asia Languages Matter

**Comment by JunnanZ** [comment]
People in the other thread keep saying this is a server issue. How is that related to this PR?

**Comment by wizdzz** [comment]
Have you guys just think about add an option for us to switch this function?

**Pull request closed without merging**
