### PR TITLE
Add default text answers

### PR DESCRIPTION
**Pull request by Vahn84**
for Android Wear Notifications

### CODE REVIEW

**Comment by robin0van0der0v** [comment]
Looks good. Maybe some more replies?

**Comment by Vahn84** [comment]
I was out of ideas

would you suggest me some useful answers?

**Comment by Bikonja** [comment]
The most sane suggestion would be an entry in the settings where every user could enter his/her own replies for Android wear. I personally love when there are just basic ones out of the box and I can really personalize my responses, otherwise there's no point in scrolling through a bunch of replies I never use only to get to the replies I added myself. Of course, this means more code... Otherwise, I absolutely support this and even like this, I would be happy if the pull request is merged into Telegram.

**Comment by Vahn84** [comment]
@Bikonja 

considered your request, and i'm adding that feature. I will open a new pull request

**Pull request closed without merging**
