### PR TITLE
Stock emoji set

### PR DESCRIPTION
**Pull request by robin0van0der0v**
Added an option to use the stock emoji set.
#624

### CODE REVIEW

**Comment by Multimoon** [comment]
I'm baffled why this is such a debate. There is no right or wrong over which set is better. Simply leave the iOS pack in the app. And implement a setting to use stock system emojiis. I assume you've heard of the GNOME project? with the release of 3.0 years ago, they attempted to force their opinion on users. It didn't go well.

**Comment by DrFiz** [comment]
As an Android user and Telegram lover I'd like to see merged this pull request

I honestly like more Android emojis, but... what if everybody could use the preferred emoji set and the receiver actually see the emote as sent from the sender?
"What I send is what you see" principle :wink:

**Comment by wp9015362** [comment]
As already mentioned in:

https://github.com/DrKLO/Telegram/issues/829

and:

https://github.com/DrKLO/Telegram/issues/222

please do not merge this.

**Comment by Multimoon** [comment]
@wp9015362 this is a helpful change, it should be merged, and this clearly isn't a problem otherwise the powers that be would have standardized Emojiis for you know, everything else? Such as SMS/MMS.

**Comment by desick** [comment]
I would love for this to be merged into the app. 
Please Please merge this, or at least add the option to use iOS versus Android.

**Comment by wp9015362** [comment]
> @Multimoon wrote:
>
> this is a helpful change, it should be merged, and this clearly isn't a problem

It is not helpful and it clearly is a problem as he even wanted to force the native Emojis on users, see:

>  @robin0van0der0v wrote:
> 
> @midi Indeed, I think this is a much better solution to his problem than this one.
> That way we don't add a extra setting for solving such a small thing.
> 
> @DrKLO What do you think? A extra setting to use the native emoji set _or_
> always using the native emoji set when it is available?

So, as you can see, he even was thinking about forcing it instead of making it optional.

So much about "choice"...

**Comment by nastys** [comment]
Why not merge? It's optional, after all. If you don't want to use system emojis, then just don't enable that option.
(it's much better than forking the app just to use system emojis)

**Comment by wp9015362** [comment]
> @nastys wrote:
> 
> Why not merge? It's optional, after all. If you don't want
> to use system emojis, then just don't enable that option.

Even if I would not enable such an option, then still my chat partner could have enabled it and then his/her Emojis probably would look different than the ones I would be using. And when each chat partner has different Emojis it can lead to confusion.

It's all explained in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

**Comment by nastys** [comment]
@wp9015362 I know some emojis may be different and that's why I think this should be disabled by default and possibly show a warning when enabling it. Using stock emojis has its advantages: for instance, they render faster (useful for old devices) and they look nicer with material design than Apple emojis. Anyway, Android Lollipop fixed some inconsistencies between the two sets and some devices use their own set.

**Comment by wp9015362** [comment]
@nastys 

This is all being discussed over there:

https://github.com/DrKLO/Telegram/issues/829

**Comment by Pox1994** [comment]
iOS emojis are so out of place in Material Design, they ruin user experience.

**Comment by Walkman100** [comment]
https://play.google.com/store/apps/details?id=me.swineson.moegram.messenger

**Comment by indrora** [comment]
Since this will get to people: @DrKLO has killed the issue tracker, hiding (nee destroying) history.

**Comment by 9peppe** [comment]
What. The. Hell.

I don't get why there are such strong feelings about this. There are at least 4 pull requests doing this in differing ways, one even includes an emoji pack selector instead of a switch to choose natives, and nonetheless, DrKLO does not want to merge this, replying "fork or die" because "apple did it first;" bullshit: ntt docomo did it first, and Unicode controls it.

How many telegram forks do we need? The official one has apple emoji, Telegram-FOSS does not have GMS, that I wanted. Do I need to make a THIRD one?

**Comment by Multimoon** [comment]
Yes @9peppe , the general attitude from @DrKLO has been very defensive with the 'write your own and gtfo' attitude. As a developer with a few apps on the play store myself, if I user asks me to implement a option to allow for one of their preferences I always do, and I have yet to have any complaints of that. Even where Emojiis are involved.

**Comment by thepaperpilot** [comment]
I would love to see the native emoji set used. Being native means it will automatically update when the system updates, is easier on everyone's device, and will make the app fit in more with the system its on. After doing so much to make telegram look like it belongs on each system, having universal apple emojis is a huge contrast. It also means people that change the system emojis because they prefer them will see their change reflected in telegram, which would be great. I don't think its a large issue if you can't see what the emoji will look like on the other users' end(s), because you are sending a unicode symbol, which is supposed to be separate from the implementation.

As others have said, if you are going to force a universal standard, it should definitely be one with an open license, like Noto.

**Comment by Walkman100** [comment]
@9peppe you mean a fourth one, third one is: https://play.google.com/store/apps/details?id=me.swineson.moegram.messenger

**Comment by tremby** [comment]
Since issues have disappeared I'll reiterate my comment on #829 here:

It seems the only real argument for using a single set of emoji on all platforms is so that everyone sees the same thing. But this is a false argument: this is an open protocol, and the person you're speaking to may not be using an official client. They might be in a text-only terminal, or using some web interface or bridge or any number of other possibilities. They might be using the official client but a newer or older version which displays the emojis differently.

So since there's no guarantee everyone sees the same thing I can't see any real argument against using the stock emoji set on each platform other than "I don't like this set". If "I don't like this set" is a common complaint, offer the choice. It seems very straightforward.

**Comment by brownsmart** [comment]
Here is a question, why is the android version the only one where i cant change the colour of the emoji?

**Comment by The0x539** [comment]
Because neither Android itself nor the app, with its nonsensically baked-in solution, support skin tone emoji yet.

**Comment by brownsmart** [comment]
@The0x539 ... The app yes does not support it, but Android does because I can use it on WhatsApp, so I fail to see why it cant be done on Telegram too.

**Comment by The0x539** [comment]
That app does support it.

**Comment by brownsmart** [comment]
Your not making any sense... you previously said "Because neither Android itself nor the app, with its nonsensically baked-in solution, support skin tone emoji yet."

Which means neither Android or Telegram "the app" support it, now you saying the app does? ... so therefore what's the hold up?

**Comment by The0x539** [comment]
It's supported by WA's implementation, but not that of Android or Telegram.

**Comment by brownsmart** [comment]
Which translates to... not any time soon then? :joy:

**Comment by brownsmart** [comment]
I stand corrected, Well done @DrKLO very greatful for the skin tone emoji addition. 👊

**Comment by Multimoon** [comment]
I saw the new emojiis change and I got excited hoping that there were finally new emojiis or the ability to use your own. Then I saw it was just the useless skintone.

**Comment by brownsmart** [comment]
@Multimoon useless to you, but to me a long awaited update. What other new emjoi's where you wanting?

**Comment by Multimoon** [comment]
Hmm, maybe the ability to use stock system emojiis, like we've all been
begging and fighting for, for upwards of a year?

**Comment by brownsmart** [comment]
If you refering to the stock android emoji, I always thought those were, boring and not fit for purpose...

**Comment by The0x539** [comment]
The issue, though, is that that's an opinion.

**Comment by brownsmart** [comment]
Good point.

**Comment by private-static-void** [comment]
Having the toggle there for people who do want stock Android wouldn't affect anyone negatively. It should be added for the sake of those who have a preference for the Android ones.

**Comment by tremby** [comment]
@robin0van0der0v, can you comment on the reason you closed this?

**Comment by robin0van0der0v** [comment]
@tremby Because @DrKLO (or somebody else of Telegram) already made the decision more than a year ago to not implement this and hasn't responded since and because this pull request was pretty outdated anyway.

**Comment by tjhorner** [comment]
There's also an alternative called Plus Messenger that allows this feature.

**Comment by tremby** [comment]
Yeah, I'm aware there are a few. I'm using [Moegram](https://play.google.com/store/apps/details?id=me.swineson.moegram.messenger&hl=en) currently. But I'd still much rather this feature made it upstream.

**Pull request closed without merging**
