### PR TITLE
Add French Translation (fixed)

### PR DESCRIPTION
**Pull request by xavihernandez**
Correction of french translation

### CODE REVIEW

**Comment by fgallaire** [comment]
Hello, why is this still not merged ??

**Comment by barreeeiroo** [comment]
I would guess because translations are done here:
https://www.transifex.com/telegram/telegram/
Then the team marges that changes

**Comment by fgallaire** [comment]
I'm very surprised, more than 200 millions of french speakers in the world and nobody in the Telegram team seems to care about the french translation ?

What should we do to move forward ?

**Comment by jlsjonas** [comment]
@fgallaire as mentioned by barreeeiroo, translations happen on transifex, if you want to help translating, join them there ;) https://www.transifex.com/signup/?join_project=telegram

**Comment by fgallaire** [comment]
> join them there ;) https://www.transifex.com/signup/?join_project=telegram

@jlsjonas @barreeeiroo How can I do it if nobody accept me in the team ??

**Comment by fgallaire** [comment]
Since 4.4, Telegram supports french:
https://telegram.org/blog/live-locations

**Pull request closed without merging**
