### PR TITLE
Fix incorrect unread messages counter

### PR DESCRIPTION
**Pull request by IAmKapuze**
Table "messages" in cache4.db doesn't keep all unread messages. If, for example, any channel have 100 unread messages, table "messages" may content only one (then COUNT(mid) will be = 1). Because of this, counter may display an incorrect value after update.
I found the "still_unread_count" field in TL_updateReadChannelInbox and TL_updateReadHistoryInbox, the use of which solves the problem, but I don't know why it's not used.
Maybe there is a preferred way to solve the problem?

### CODE REVIEW

**Comment by IAmKapuze** [comment]
Added a description (with video) of the problem at the link:
https://bugs.telegram.org/c/4849

**Comment by nizomovasadbek** [comment]
Hello I have an idea

Yak, 2-may, 2021, 19:27 IAmKapuze ***@***.***>:

**Review by 22072012 — APPROVED** [review]

**Comment by Playez** [comment]
You should ping @xaxtix , drklo doesnt work on telegram android client rn,
xaxtix does it

вт, 11 янв. 2022 г., 6:28 PM Alexandr Keyp ***@***.***>:

**Comment by IAmKapuze** [comment]
@xaxtix, tdlib use still_unread_count variable to update messages counter. May be, this code can be taken as a basis ?
https://github.com/tdlib/td/blob/master/td/telegram/MessagesManager.cpp#L6598

**Comment by IAmKapuze** [comment]
Fixed in 8.9.0

**Pull request closed without merging**
