### PR TITLE
Update CameraView.java

### PR DESCRIPTION
**Pull request by NooAn**
circleShape don't uses here

### CODE REVIEW

**Comment by ArashParsayar** [comment]
Hey, that's a good idea, a few tiny alterations need to be addressed but unfortunately it's been almost 6 months since the last official commit, is it gonna come out at any time soon?

**Comment by agentsib** [comment]
The project is dead) Look at last commit version date :)

**Comment by ArashParsayar** [comment]
That's a shame, lots of new features has been added since 4.6.0...

I Hope Someone in their development team remembers there is a repo here... ;)

**Comment by brownstic** [comment]
I lost all hope. Its sad really that Telegram dont care anymore. It could be that they dont want people to see their code because they are hiding something. But anyway this repo is dead

**Comment by dkaraush** [comment]
I see it was merged, thanks!

**Pull request closed without merging**
