### PR TITLE
Fix voice message sample rate (again)

### PR DESCRIPTION
**Pull request by sermart1234**
https://github.com/DrKLO/Telegram/pull/1566
But voice messages still use 16kHz. I set 48 kHz.

### CODE REVIEW

**Review by egormanga — APPROVED** [review]

**Comment by itsreallyv1eds** [comment]
in almost all modified clients this is done, and they even do it in the first place. I think if this is added to the official client, it will not become superfluous, especially since there are no complaints

**Review by itsreallyv1eds — APPROVED** [review]
in almost all modified clients this is done, and they even do it in the first place. I think if this is added to the official client, it will not become superfluous, especially since there are no complaints

**Comment by Attorelle** [comment]
@AlexandrKozlovskiy previously suggested this, with better voice processing in #1644 :)

**Review by Playez — APPROVED** [review]
### 

- [x] 1. > [`_****_`](url)

**Comment by dkaraush** [comment]
I see this was merged, thanks for the PR!

**Pull request closed without merging**
